export const data = {
  p1: "p1",
  p1content:
    "The heritage of Chirakadavil Family, Elanthiir has its legacy to the landing of Apostle Thomas at Kodungalloor, Kerala in AD 52 and subsequent conversion of four Brahmin families to Christianity viz, Kali, Kaliyangal,Ã‚Â  Shankarapuri and Pakalomattam. Our patriarch Shri. Mathan was from Nilackal (a Brahmin converted Christian settlement) which now falls under the jurisdiction of Pathanamthitta revenue district. The Nilackal PalliÃ‚Â (now extinct) is considered to be one of the 7 1/2 churches founded by St. Thomas himself. Due to constant attacks from wild animals and threats of Pandi bandits nick named “Parappatta”, the ancient settlers had to flee to safer places like Kadambanadu and Chengannur etc. The peace-loving forefathers were accepted whole heartedly by local rulers and people alike wherever they preferred to settle at Around 380 years ago, our patriarch Shri. Mathan along with his wife leftÃ‚Â  Chiarakadavu near Kanjirappally and settled at Elanthoor where more than sixteen Brahmin illams then existed. Having hailed from Chirakadavu, local people respectfully called him Chirakadavil Mathan. That was the humble beginning of The Chirakadavil Family. Hardwork, dedication and above all Godliness earned Mathan fame and acceptance among people. Gradually he amassed many landed properties in Elanthoor. He was morally upright, social reformist and above all a staunch follower of Jesus Christ. That is the reason the Chirakadavil Family has been blessed with a number of priests, pastors, evangelists and upright political activists. Surprisingly, one will rarely trace any presence of anti-social elements in the family history, hitherto. The Mathan Family was blessed with three sons who settled in three divisions of the family owned land.",
  p2: "p2",
  p2content:
    "Eldest son Mathan Itty shifted to the southern end of the land and known as Thekkel Mathan Itty ii) The second son continued to stay in the same family house and was known as Chirakadavil Mathan Koshyiii) The youngest son moved to the northern portion was known as Vadakkel Matan Cherian. Thus the three sons of Chirakadavil Mathan had become the Branch Heads of Thekkel, Chirakadavil and Vadakkel branches of the family. Henceforth, (for the sake of brevity) we may restrict our descriptions to the Thekkel Branch of the family consisting of Thekkel Mathan Itty and his descendants. Please refer ‘Chirakadavil Kudumba Charithram’ (Malayalam) published in 1991 for a branch by branch history.",


};
